language: go

os:
  - linux

services:
  - docker

before_install:
  - make docker_container

script:
  - make release

deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  on:
    tags: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - ./*.zip
    - ./*.tar.gz
