name: Build

on:
  push:
    branches:
    - master
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Install jq tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-mingw-w64

    - name: Build
      run: |
        make linux
        make windows
