name: Build

on:
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  build_linux_and_windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Install cross-compiling libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-mingw-w64

    - name: Build
      run: |
        make release_linux
        make release_windows
        
  build_macos:
    runs-on: macos-latest 
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Build
      run: |
        make release_darwin
